---
abstract: 'Log appender for posting job to gearman'
author:
  - 'Chia-liang Kao, C<< <clkao at clkao.org> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.95'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Log-Log4perl-Appender-Gearman
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Gearman::Client: 0
  Log::Log4perl: 0
  perl: 5.8.8
resources:
  license: http://dev.perl.org/licenses/
  repository: git.bestpractical.com:/git/log-log4perl-appender-gearman.git
version: 0.29
